# Generated by Django 4.2.3 on 2023-07-18 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('score', models.IntegerField(default=0)),
                ('ratings', models.IntegerField(default=0)),
                ('reviews', models.IntegerField(default=0)),
                ('appId', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('categories', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'app_details_tb',
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(blank=True, max_length=250, null=True)),
                ('developerId', models.CharField(blank=True, max_length=250, null=True)),
                ('developerEmail', models.CharField(blank=True, max_length=150, null=True)),
                ('developerWebsite', models.CharField(blank=True, max_length=50, null=True)),
                ('developerAddress', models.CharField(blank=True, max_length=250, null=True)),
                ('app_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper_app.appdetails')),
            ],
            options={
                'db_table': 'developer_tb',
            },
        ),
    ]
